In [55]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/muhammadshahidazeem/customer-churn-dataset/customer_churn_dataset-testing-master.csv
/kaggle/input/datasets/muhammadshahidazeem/customer-churn-dataset/customer_churn_dataset-training-master.csv

In [56]:
df = pd.read_csv("/kaggle/input/datasets/muhammadshahidazeem/customer-churn-dataset/customer_churn_dataset-testing-master.csv")
print(df.head())

   CustomerID  Age  Gender  Tenure  Usage Frequency  Support Calls  \
0           1   22  Female      25               14              4
1           2   41  Female      28               28              7
2           3   47    Male      27               10              2
3           4   35    Male       9               12              5
4           5   53  Female      58               24              9

   Payment Delay Subscription Type Contract Length  Total Spend  \
0             27             Basic         Monthly          598
1             13          Standard         Monthly          584
2             29           Premium          Annual          757
3             17           Premium       Quarterly          232
4              2          Standard          Annual          533

   Last Interaction  Churn
0                 9      1
1                20      0
2                21      0
3                18      0
4                18      0

In [57]:
#df.shape
#df.info
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency',
       'Support Calls', 'Payment Delay', 'Subscription Type',
       'Contract Length', 'Total Spend', 'Last Interaction', 'Churn'],
      dtype='object')

In [58]:
df.dtypes

CustomerID            int64
Age                   int64
Gender               object
Tenure                int64
Usage Frequency       int64
Support Calls         int64
Payment Delay         int64
Subscription Type    object
Contract Length      object
Total Spend           int64
Last Interaction      int64
Churn                 int64
dtype: object

In [59]:
df.duplicated().sum()

np.int64(0)

In [60]:
df['Churn'].value_counts()

Churn
0    33881
1    30493
Name: count, dtype: int64

In [61]:
print(df['Subscription Type'].value_counts())
print("\n")
print(df['Contract Length']. value_counts())
print("\n")
print(df["Last Interaction"].value_counts())

Subscription Type
Standard    21502
Basic       21451
Premium     21421
Name: count, dtype: int64


Contract Length
Monthly      22130
Annual       21410
Quarterly    20834
Name: count, dtype: int64


Last Interaction
7     2291
8     2210
30    2206
16    2201
11    2195
13    2176
20    2169
17    2162
3     2162
21    2160
22    2159
6     2158
15    2157
26    2153
29    2149
27    2148
25    2145
14    2143
18    2137
10    2134
19    2133
2     2118
12    2118
1     2116
23    2094
24    2091
9     2088
5     2087
4     2058
28    2056
Name: count, dtype: int64

In [62]:
df.drop(columns=['CustomerID'],inplace=True)

In [63]:
df.head()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [64]:
df=pd.get_dummies(df,columns=['Gender', 'Subscription Type', 'Contract Length'],drop_first=True,dtype=int)

In [70]:
# Scaling 
X= df.drop(columns=['Churn'])
Y= df['Churn']

In [79]:
X

,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Gender_Male,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Monthly,Contract Length_Quarterly
0,22,25,14,4,27,598,9,0,0,0,1,0
1,41,28,28,7,13,584,20,0,0,1,1,0
2,47,27,10,2,29,757,21,1,1,0,0,0
3,35,9,12,5,17,232,18,1,1,0,0,1
4,53,58,24,9,2,533,18,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
64369,45,33,12,6,21,947,14,0,0,0,0,1
64370,37,6,1,5,22,923,9,1,0,1,0,0
64371,25,39,14,8,30,327,20,1,1,0,1,0
64372,50,18,19,7,22,540,13,0,0,1,1,0
64373,52,45,15,9,25,696,22,0,0,1,1,0

In [71]:
X_train,X_test, Y_train, Y_test = train_test_split(X, Y , test_size=0.2, random_state=1)

In [72]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [73]:
X_train_scaled

array([[-2.86459005e-01, -8.16992933e-01,  1.01651676e+00, ...,
        -7.07992583e-01, -7.23753678e-01, -6.92409704e-01],
       [ 1.07673595e+00,  8.40535878e-04, -1.25151101e+00, ...,
         1.41244417e+00,  1.38168555e+00, -6.92409704e-01],
       [-8.60435828e-01,  5.85007299e-01, -2.30898518e-01, ...,
        -7.07992583e-01, -7.23753678e-01, -6.92409704e-01],
       ...,
       [-1.64965396e+00, -5.83326228e-01, -5.71102684e-01, ...,
        -7.07992583e-01, -7.23753678e-01,  1.44423164e+00],
       [ 1.22023016e+00,  8.18674005e-01, -1.47831379e+00, ...,
         1.41244417e+00, -7.23753678e-01, -6.92409704e-01],
       [-5.73447417e-01, -5.75761405e-02,  1.69692509e+00, ...,
        -7.07992583e-01, -7.23753678e-01, -6.92409704e-01]])

In [77]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [94]:
model = Sequential()

model.add(Dense(4, activation='relu', input_dim=12))
model.add(Dense(3, activation='relu'))
model.add(Dense(2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [95]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 4)              │            52 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 3)              │            15 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 2)              │             8 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 78 (312.00 B)

 Trainable params: 78 (312.00 B)

 Non-trainable params: 0 (0.00 B)

In [96]:
#Compile model
model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])

In [97]:
model.fit(X_train_scaled, Y_train, epochs=100, validation_split=0.2)

Epoch 1/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.7934 - loss: 0.4837 - val_accuracy: 0.8466 - val_loss: 0.3717
Epoch 2/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8534 - loss: 0.3552 - val_accuracy: 0.8583 - val_loss: 0.3414
Epoch 3/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8600 - loss: 0.3336 - val_accuracy: 0.8644 - val_loss: 0.3238
Epoch 4/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8641 - loss: 0.3214 - val_accuracy: 0.8610 - val_loss: 0.3160
Epoch 5/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8654 - loss: 0.3137 - val_accuracy: 0.8674 - val_loss: 0.3086
Epoch 6/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8660 - loss: 0.3088 - val_accuracy: 0.8667 - val_loss: 0.3030
Epoch 7/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8673 - loss: 0.3047 - val_accuracy: 0.8686 - val_loss: 0.2992
Epoch 8/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8678 - loss: 0.3011 - val_accuracy: 0.8695 - val_loss: 0.2969
Epoch 9/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8678 - loss: 0.2969 - val_accuracy: 0.8635 - val_loss: 0.2961
Epoch 10/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8678 - loss: 0.2925 - val_accuracy: 0.8683 - val_loss: 0.2909
Epoch 11/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8684 - loss: 0.2872 - val_accuracy: 0.8677 - val_loss: 0.2876
Epoch 12/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8688 - loss: 0.2819 - val_accuracy: 0.8683 - val_loss: 0.2830
Epoch 13/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8691 - loss: 0.2763 - val_accuracy: 0.8682 - val_loss: 0.2766
Epoch 14/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8706 - loss: 0.2674 - val_accuracy: 0.8688 - val_loss: 0.2674
Epoch 15/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8836 - loss: 0.2548 - val_accuracy: 0.8937 - val_loss: 0.2514
Epoch 16/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9001 - loss: 0.2400 - val_accuracy: 0.8984 - val_loss: 0.2388
Epoch 17/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9043 - loss: 0.2265 - val_accuracy: 0.9048 - val_loss: 0.2272
Epoch 18/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9087 - loss: 0.2171 - val_accuracy: 0.9065 - val_loss: 0.2207
Epoch 19/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9084 - loss: 0.2114 - val_accuracy: 0.9059 - val_loss: 0.2158
Epoch 20/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9098 - loss: 0.2070 - val_accuracy: 0.9093 - val_loss: 0.2109
Epoch 21/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9117 - loss: 0.2036 - val_accuracy: 0.9096 - val_loss: 0.2066
Epoch 22/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9119 - loss: 0.2011 - val_accuracy: 0.9111 - val_loss: 0.2045
Epoch 23/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9123 - loss: 0.1988 - val_accuracy: 0.9120 - val_loss: 0.2010
Epoch 24/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9127 - loss: 0.1966 - val_accuracy: 0.9113 - val_loss: 0.1986
Epoch 25/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9134 - loss: 0.1949 - val_accuracy: 0.9122 - val_loss: 0.1976
Epoch 26/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9137 - loss: 0.1934 - val_accuracy: 0.9126 - val_loss: 0.1969
Epoch 27/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9139 - loss: 0.1923 - val_accuracy: 0.9125 - val_loss: 0.1951
Epoch 28/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9135 - loss: 0.1912 - val_accuracy: 0.9142 - val_loss: 0.1937
Epoch 29/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9138 - loss: 0.1904 - val_accuracy: 0.9144 - val_loss: 0.1928
Epoch 30/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9149 - loss: 0.1899 - val_accuracy: 0.9158 - val_loss: 0.1927
Epoch 31/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9150 - loss: 0.1889 - val_accuracy: 0.9145 - val_loss: 0.1920
Epoch 32/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9144 - loss: 0.1888 - val_accuracy: 0.9144 - val_loss: 0.1914
Epoch 33/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9152 - loss: 0.1881 - val_accuracy: 0.9149 - val_loss: 0.1896
Epoch 34/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9150 - loss: 0.1883 - val_accuracy: 0.9155 - val_loss: 0.1917
Epoch 35/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9149 - loss: 0.1876 - val_accuracy: 0.9142 - val_loss: 0.1903
Epoch 36/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9157 - loss: 0.1871 - val_accuracy: 0.9143 - val_loss: 0.1893
Epoch 37/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9162 - loss: 0.1870 - val_accuracy: 0.9156 - val_loss: 0.1897
Epoch 38/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9149 - loss: 0.1869 - val_accuracy: 0.9134 - val_loss: 0.1897
Epoch 39/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9162 - loss: 0.1860 - val_accuracy: 0.9165 - val_loss: 0.1870
Epoch 40/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9166 - loss: 0.1856 - val_accuracy: 0.9176 - val_loss: 0.1880
Epoch 41/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9162 - loss: 0.1856 - val_accuracy: 0.9132 - val_loss: 0.1895
Epoch 42/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9155 - loss: 0.1860 - val_accuracy: 0.9169 - val_loss: 0.1881
Epoch 43/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9165 - loss: 0.1855 - val_accuracy: 0.9162 - val_loss: 0.1885
Epoch 44/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9166 - loss: 0.1849 - val_accuracy: 0.9168 - val_loss: 0.1954
Epoch 45/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9153 - loss: 0.1854 - val_accuracy: 0.9158 - val_loss: 0.1866
Epoch 46/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9166 - loss: 0.1843 - val_accuracy: 0.9178 - val_loss: 0.1879
Epoch 47/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9166 - loss: 0.1847 - val_accuracy: 0.9164 - val_loss: 0.1860
Epoch 48/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9164 - loss: 0.1845 - val_accuracy: 0.9162 - val_loss: 0.1870
Epoch 49/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9163 - loss: 0.1844 - val_accuracy: 0.9155 - val_loss: 0.1862
Epoch 50/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9173 - loss: 0.1842 - val_accuracy: 0.9171 - val_loss: 0.1879
Epoch 51/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9161 - loss: 0.1843 - val_accuracy: 0.9165 - val_loss: 0.1881
Epoch 52/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9172 - loss: 0.1840 - val_accuracy: 0.9144 - val_loss: 0.1872
Epoch 53/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9178 - loss: 0.1838 - val_accuracy: 0.9164 - val_loss: 0.1852
Epoch 54/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9169 - loss: 0.1841 - val_accuracy: 0.9167 - val_loss: 0.1861
Epoch 55/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9164 - loss: 0.1838 - val_accuracy: 0.9176 - val_loss: 0.1854
Epoch 56/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9167 - loss: 0.1837 - val_accuracy: 0.9137 - val_loss: 0.1894
Epoch 57/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9163 - loss: 0.1833 - val_accuracy: 0.9177 - val_loss: 0.1882
Epoch 58/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9175 - loss: 0.1835 - val_accuracy: 0.9165 - val_loss: 0.1873
Epoch 59/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9163 - loss: 0.1836 - val_accuracy: 0.9170 - val_loss: 0.1846
Epoch 60/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9171 - loss: 0.1836 - val_accuracy: 0.9172 - val_loss: 0.1873
Epoch 61/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9172 - loss: 0.1835 - val_accuracy: 0.9176 - val_loss: 0.1864
Epoch 62/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9173 - loss: 0.1829 - val_accuracy: 0.9164 - val_loss: 0.1868
Epoch 63/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9168 - loss: 0.1832 - val_accuracy: 0.9170 - val_loss: 0.1885
Epoch 64/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9173 - loss: 0.1831 - val_accuracy: 0.9167 - val_loss: 0.1843
Epoch 65/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9172 - loss: 0.1830 - val_accuracy: 0.9184 - val_loss: 0.1850
Epoch 66/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9175 - loss: 0.1832 - val_accuracy: 0.9186 - val_loss: 0.1863
Epoch 67/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9171 - loss: 0.1833 - val_accuracy: 0.9155 - val_loss: 0.1855
Epoch 68/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9170 - loss: 0.1830 - val_accuracy: 0.9179 - val_loss: 0.1841
Epoch 69/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9174 - loss: 0.1831 - val_accuracy: 0.9185 - val_loss: 0.1846
Epoch 70/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9173 - loss: 0.1830 - val_accuracy: 0.9150 - val_loss: 0.1884
Epoch 71/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9169 - loss: 0.1831 - val_accuracy: 0.9167 - val_loss: 0.1865
Epoch 72/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9166 - loss: 0.1828 - val_accuracy: 0.9166 - val_loss: 0.1838
Epoch 73/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9177 - loss: 0.1831 - val_accuracy: 0.9180 - val_loss: 0.1827
Epoch 74/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9176 - loss: 0.1831 - val_accuracy: 0.9168 - val_loss: 0.1832
Epoch 75/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9186 - loss: 0.1830 - val_accuracy: 0.9149 - val_loss: 0.1874
Epoch 76/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9173 - loss: 0.1829 - val_accuracy: 0.9181 - val_loss: 0.1836
Epoch 77/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9181 - loss: 0.1826 - val_accuracy: 0.9152 - val_loss: 0.1867
Epoch 78/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9178 - loss: 0.1828 - val_accuracy: 0.9172 - val_loss: 0.1864
Epoch 79/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9179 - loss: 0.1823 - val_accuracy: 0.9150 - val_loss: 0.1870
Epoch 80/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9176 - loss: 0.1822 - val_accuracy: 0.9172 - val_loss: 0.1838
Epoch 81/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9183 - loss: 0.1821 - val_accuracy: 0.9168 - val_loss: 0.1847
Epoch 82/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9180 - loss: 0.1823 - val_accuracy: 0.9187 - val_loss: 0.1837
Epoch 83/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9173 - loss: 0.1823 - val_accuracy: 0.9166 - val_loss: 0.1885
Epoch 84/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9168 - loss: 0.1824 - val_accuracy: 0.9156 - val_loss: 0.1842
Epoch 85/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9166 - loss: 0.1825 - val_accuracy: 0.9189 - val_loss: 0.1838
Epoch 86/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9180 - loss: 0.1824 - val_accuracy: 0.9172 - val_loss: 0.1850
Epoch 87/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9164 - loss: 0.1826 - val_accuracy: 0.9183 - val_loss: 0.1862
Epoch 88/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9174 - loss: 0.1822 - val_accuracy: 0.9185 - val_loss: 0.1828
Epoch 89/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9168 - loss: 0.1822 - val_accuracy: 0.9172 - val_loss: 0.1847
Epoch 90/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9175 - loss: 0.1826 - val_accuracy: 0.9202 - val_loss: 0.1840
Epoch 91/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9180 - loss: 0.1822 - val_accuracy: 0.9161 - val_loss: 0.1885
Epoch 92/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9177 - loss: 0.1825 - val_accuracy: 0.9160 - val_loss: 0.1850
Epoch 93/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9178 - loss: 0.1819 - val_accuracy: 0.9174 - val_loss: 0.1842
Epoch 94/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9168 - loss: 0.1824 - val_accuracy: 0.9190 - val_loss: 0.1832
Epoch 95/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9157 - loss: 0.1826 - val_accuracy: 0.9196 - val_loss: 0.1828
Epoch 96/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9176 - loss: 0.1824 - val_accuracy: 0.9169 - val_loss: 0.1844
Epoch 97/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9170 - loss: 0.1825 - val_accuracy: 0.9184 - val_loss: 0.1828
Epoch 98/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9173 - loss: 0.1817 - val_accuracy: 0.9162 - val_loss: 0.1856
Epoch 99/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9183 - loss: 0.1825 - val_accuracy: 0.9170 - val_loss: 0.1829
Epoch 100/100
1288/1288 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9169 - loss: 0.1820 - val_accuracy: 0.9164 - val_loss: 0.1842

In [100]:
model.layers[3].get_weights()

[array([[-2.346149 ],
        [ 1.4193414]], dtype=float32),
 array([3.2830026], dtype=float32)]

In [101]:
y_log = model.predict(X_test_scaled)

403/403 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [102]:
y_pred = np.where(y_log>0.5, 1, 0)

In [103]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, y_pred)

0.9153398058252428